# Generated by Django 3.1.6 on 2021-02-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_log.topic'),
        ),
    ]
